
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author INSTRUCTOR
 */
public final class ListaParqueaderos extends javax.swing.JPanel {

    /**
     * Creates new form ListaParqueaderos
     */
    JsonObject datosParquedero;
    DefaultTableModel modelo;
    Gson gson = new Gson();
    ConsumoAPI conexion = new ConsumoAPI();
    public ListaParqueaderos() {
        this.datosParquedero = getDatosParqueaderoAdmin();
        initComponents();
        modelo = (DefaultTableModel) Parqueaderos.getModel();
        
        initComponentsAlter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etq_titulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Parqueaderos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        etq_titulo.setFont(new java.awt.Font("SansSerif", 0, 36)); // NOI18N
        etq_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etq_titulo.setText("Parqueaderos");
        etq_titulo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(49, 138, 222)));

        Parqueaderos.setAutoCreateRowSorter(true);
        Parqueaderos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Direccion", "Ta Motos", "Ta Carros", "Ta Camionetas", "Ta Camiones", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Parqueaderos.setEnabled(false);
        Parqueaderos.setGridColor(new java.awt.Color(49, 138, 222));
        Parqueaderos.setRequestFocusEnabled(false);
        Parqueaderos.setRowHeight(25);
        Parqueaderos.setUpdateSelectionOnSort(false);
        Parqueaderos.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(Parqueaderos);
        if (Parqueaderos.getColumnModel().getColumnCount() > 0) {
            Parqueaderos.getColumnModel().getColumn(0).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(1).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(2).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(2).setPreferredWidth(10);
            Parqueaderos.getColumnModel().getColumn(3).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(3).setPreferredWidth(10);
            Parqueaderos.getColumnModel().getColumn(4).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(4).setPreferredWidth(10);
            Parqueaderos.getColumnModel().getColumn(5).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(5).setPreferredWidth(10);
            Parqueaderos.getColumnModel().getColumn(6).setResizable(false);
            Parqueaderos.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(etq_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(etq_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void initComponentsAlter(){
        
        modelo.setNumRows(0);
        try {
            if (datosParquedero != null) {
                JsonObject jsonObject = gson.fromJson(datosParquedero, JsonObject.class);
                JsonArray registros = jsonObject.getAsJsonArray("registros");

                for (JsonElement registro : registros) {
                    JsonObject registrosOb = registro.getAsJsonObject();

                    String nombre = registrosOb.get("nombre").getAsString();
                    String direccion = registrosOb.get("direccion").getAsString();
                    String carro = registrosOb.get("carro").getAsString();
                    String moto = registrosOb.get("moto").getAsString();
                    String camioneta = registrosOb.get("camioneta").getAsString();
                    String camiones = registrosOb.get("camiones").getAsString();
                    String estado = registrosOb.get("estado").getAsString();
                    if (estado.equals("1")) {
                        estado = "Activo";

                    }else{
                        estado = "Inactivo";

                    }

                    Object[] fila = new Object[]{nombre, direccion, carro, moto, camioneta, camiones,estado};
                    modelo.addRow(fila);
                    
                    centrarTextTabla();
                }
            } else {
                System.out.println("La variable datosParquedero es nula.");
            }
        } catch (Exception e) {
            System.out.println(e.toString());
        }
        


    }
    
    private void centrarTextTabla() {
        JTableHeader header = Parqueaderos.getTableHeader();
        header.setBackground(new Color(49, 138, 222)); 
        header.setForeground(Color.WHITE);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < Parqueaderos.getColumnCount(); i++) {
            Parqueaderos.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        Parqueaderos.repaint();
        
        
    }
    
    public JsonObject getDatosParqueaderoAdmin() {
        JsonObject parqueadero = null;
        
        try {
            String temporal = conexion.consumoGET("http://localhost/APIparqueadero/parqueaderos/getParqueaderos.php");
            
            JsonObject jsonObject = gson.fromJson(temporal, JsonObject.class);
            parqueadero = jsonObject;            

        } catch (Exception e) {
            System.out.println("Error en getDatosParqueadero");
        }
        return parqueadero;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Parqueaderos;
    private javax.swing.JLabel etq_titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
