/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package principal;

import clases.ButtonEditor;
import clases.ButtonRenderer;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author INSTRUCTOR
 */
public class PbuscarVehiculo extends javax.swing.JPanel {

    /**
     * Creates new form PbuscarVehiculo
     */
    ConsumoAPI conexion = new ConsumoAPI();
    Gson gson = new Gson();
    DefaultTableModel tableModel;

    public PbuscarVehiculo() {
        initComponents();
        initComponentsAltern();
        llenarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_parqueaderos = new javax.swing.JTable();
        btn_buscar = new javax.swing.JButton();
        campo_placa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        etq_mensaje = new javax.swing.JLabel();
        btn_restablecer = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tabla_parqueaderos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PLACA", "PROPIETARIO", "TIPO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_parqueaderos.setFocusable(false);
        tabla_parqueaderos.setRowHeight(25);
        jScrollPane1.setViewportView(tabla_parqueaderos);
        if (tabla_parqueaderos.getColumnModel().getColumnCount() > 0) {
            tabla_parqueaderos.getColumnModel().getColumn(0).setResizable(false);
            tabla_parqueaderos.getColumnModel().getColumn(1).setResizable(false);
            tabla_parqueaderos.getColumnModel().getColumn(2).setResizable(false);
        }

        btn_buscar.setBackground(Color.decode("#318ade"));
        btn_buscar.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btn_buscar.setForeground(new java.awt.Color(255, 255, 255));
        btn_buscar.setText("BUSCAR");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.setFocusable(false);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        campo_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_placaActionPerformed(evt);
            }
        });
        campo_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campo_placaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Lista Vehiculos");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(49, 138, 222)));

        etq_mensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        etq_mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btn_restablecer.setBackground(new java.awt.Color(255, 102, 102));
        btn_restablecer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_restablecer.setForeground(new java.awt.Color(255, 255, 255));
        btn_restablecer.setText("X");
        btn_restablecer.setBorder(null);
        btn_restablecer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_restablecer.setFocusable(false);
        btn_restablecer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restablecerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etq_mensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(campo_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_buscar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_restablecer, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(etq_mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campo_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_restablecer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        buscarParqueadero();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void campo_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_placaActionPerformed

    private void campo_placaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campo_placaKeyPressed
        if (evt.getKeyChar() == '\n') {
            System.out.println("Se presiono enter y buscar el parqueadero");
            buscarParqueadero();
        }
    }//GEN-LAST:event_campo_placaKeyPressed

    private void btn_restablecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restablecerActionPerformed
        llenarTabla();
    }//GEN-LAST:event_btn_restablecerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_restablecer;
    private javax.swing.JTextField campo_placa;
    private javax.swing.JLabel etq_mensaje;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_parqueaderos;
    // End of variables declaration//GEN-END:variables

    private void initComponentsAltern() {
        JTableHeader header = tabla_parqueaderos.getTableHeader();
        header.setBackground(new Color(49, 138, 222));
        header.setForeground(Color.WHITE);
    }

    private void buscarParqueadero() {
        etq_mensaje.setText("");

        String placa = campo_placa.getText();

        Map<String, String> dataPost = new HashMap<>();
        dataPost.put("placa", placa);
        try {
            String response = conexion.consumoPOST("http://localhost/APIparqueadero/vehiculos/findVehiculos.php", dataPost);

            System.out.println("respuesta " + response);

            JsonObject jsonObject = gson.fromJson(response, JsonObject.class);

            JsonArray registros = jsonObject.getAsJsonArray("registros");
            System.out.println(registros);
            //!registros.isEmpty()
            //registros.size() > 0
            if (registros.size() > 0) {

                tableModel = (DefaultTableModel) tabla_parqueaderos.getModel();
                tableModel.setNumRows(0);

                for (JsonElement registro : registros) {
                    JsonObject registrosOb = registro.getAsJsonObject();

                    String placaObtenida = registrosOb.get("placa").getAsString();
                    String propietario = registrosOb.get("propietario").getAsString();
                    String tipo = registrosOb.get("tipo").getAsString();

                    Object[] temporal = new Object[]{placaObtenida, propietario, tipo};
                    tableModel.addRow(temporal);

                    centrarTextTabla();

                }

            } else {
                JOptionPane.showMessageDialog(null, "No se encontraron resultados");
                llenarTabla();
            }
        } catch (Exception e) {
            etq_mensaje.setText("El vehiculo no existe");

            System.out.println("error al obtener el vehiculo" + e);
        }
        campo_placa.setText("");
    }

    private void llenarTabla() {
        try {
            String response = conexion.consumoGET("http://localhost:8080/lista-vehiculos");
            System.out.println(response);
            JsonObject jsonObject = gson.fromJson(response, JsonObject.class);

            JsonArray registros = jsonObject.getAsJsonArray("registros");
            //!registros.isEmpty()
            //registros.size() > 0
            if (registros.size() > 0) {
                tableModel = (DefaultTableModel) tabla_parqueaderos.getModel();
                tableModel.setNumRows(0);

                for (JsonElement registro : registros) {
                    JsonObject registrosOb = registro.getAsJsonObject();

                    String placaObtenida = registrosOb.get("placa").getAsString();
                    String propietario = registrosOb.get("propietario").getAsString();
                    String tipo = registrosOb.get("tipo").getAsString();

                    Object[] temporal = new Object[]{placaObtenida, propietario, tipo};
                    tableModel.addRow(temporal);

                    centrarTextTabla();

                }
            } else {

            }

        } catch (Exception e) {
            System.out.println("error al obtener el parqueadero");
        }
    }

    private void centrarTextTabla() {
        JTableHeader header = tabla_parqueaderos.getTableHeader();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);

        for (int i = 0; i < tabla_parqueaderos.getColumnCount(); i++) {
            tabla_parqueaderos.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
        tabla_parqueaderos.repaint();
    }
}
